sudo: required
dist: trusty
language: python

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-pip python-dev
  - sudo apt-get install -qq -y python-flake8

install:
  - pip install -r requirements.txt
  - python setup.py build
  - python setup.py -q install

before_script:
  - "flake8 --max-line-length=120 --max-complexity=16 --ignore=E22,E241,E731 src"

script:
  - python -m doctest src/cysignals/*.pyx
  - cd example && python setup.py install

notifications:
  on_success: change
  on_failure: always
